"""Constants for the Lizard Care integration."""

DOMAIN = "lizardcare"
MANUFACTURER = "Lizard Care"

CONF_PET_NAME = "pet_name"
CONF_NORMALIZED_PET_NAME = "normalized_pet_name"
CONF_SPECIES = "species"
CONF_BIRTH_DATE = "birth_date"
CONF_SEX = "sex"
CONF_NOTES = "notes"

DEFAULT_SPECIES = "Gargoyle Gecko"

CONF_FEEDING_INTERVAL_DAYS = "feeding_interval_days"
CONF_SPOT_CLEAN_INTERVAL_DAYS = "spot_clean_interval_days"
CONF_FULL_CLEAN_INTERVAL_DAYS = "full_clean_interval_days"

DEFAULT_FEEDING_INTERVAL_DAYS = 2
DEFAULT_SPOT_CLEAN_INTERVAL_DAYS = 7
DEFAULT_FULL_CLEAN_INTERVAL_DAYS = 30

CONF_NOTIFICATION_RECIPIENTS = "notification_recipients"
CONF_FEEDING_REMINDERS = "feeding_reminders"
CONF_SPOT_CLEAN_REMINDERS = "spot_clean_reminders"
CONF_FULL_CLEAN_REMINDERS = "full_clean_reminders"
CONF_FOOD_REMOVAL_REMINDER = "food_removal_reminder"
CONF_REMINDER_TIME = "reminder_time"
CONF_FEEDING_REMINDER_TIME = "feeding_reminder_time"
CONF_CLEANING_REMINDER_TIME = "cleaning_reminder_time"
CONF_FOOD_REMOVAL_DELAY_HOURS = "food_removal_delay_hours"
CONF_FOOD_REMOVAL_REMINDER_BASIS = "food_removal_reminder_basis"
CONF_FOOD_REMOVAL_OVERDUE_REPEAT_HOURS = (
    "food_removal_overdue_repeat_hours"
)
CONF_FEEDING_OVERDUE_REPEAT_HOURS = "feeding_overdue_repeat_hours"
CONF_SPOT_CLEAN_OVERDUE_REPEAT_HOURS = "spot_clean_overdue_repeat_hours"
CONF_FULL_CLEAN_OVERDUE_REPEAT_HOURS = "full_clean_overdue_repeat_hours"

DEFAULT_FEEDING_REMINDERS = True
DEFAULT_SPOT_CLEAN_REMINDERS = True
DEFAULT_FULL_CLEAN_REMINDERS = True
DEFAULT_FOOD_REMOVAL_REMINDER = True
DEFAULT_FEEDING_REMINDER_TIME = "19:00:00"
DEFAULT_CLEANING_REMINDER_TIME = "09:00:00"
DEFAULT_FOOD_REMOVAL_DELAY_HOURS = 12
DEFAULT_FOOD_REMOVAL_OVERDUE_REPEAT_HOURS = 1
DEFAULT_FEEDING_OVERDUE_REPEAT_HOURS = 1
DEFAULT_SPOT_CLEAN_OVERDUE_REPEAT_HOURS = 6
DEFAULT_FULL_CLEAN_OVERDUE_REPEAT_HOURS = 6

FOOD_REMOVAL_BASIS_ACTUAL = "actual_feeding_time"
FOOD_REMOVAL_BASIS_SCHEDULED = "scheduled_feeding_reminder_time"
DEFAULT_FOOD_REMOVAL_REMINDER_BASIS = FOOD_REMOVAL_BASIS_SCHEDULED

STORAGE_VERSION = 1

STATE_LAST_FED = "last_fed"
STATE_LAST_FOOD_REMOVED = "last_food_removed"
STATE_FOOD_IN_ENCLOSURE = "food_in_enclosure"
STATE_LAST_SPOT_CLEAN = "last_spot_clean"
STATE_LAST_FULL_CLEAN = "last_full_clean"
